name: qiscus_chat_sdk
description: The Scalable In-App Chat SDK for Mobile & Web
version: 1.0.18
homepage: https://sdk.qiscus.com
repository: https://github.com/qiscus/qiscus-chat-sdk-flutter
issue_tracker: https://github.com/qiscus/qiscus-chat-sdk-flutter/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sealed_unions: ^3.0.3+1
  async: ^2.5.0
  mqtt_client: ^9.4.2
  dio: ^4.0.0
  equatable: ^2.0.3
  pretty_dio_logger: ^1.2.0-beta-1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
